### ISSUE TITLE
Upload Multiple File in same URL

### ISSUE THREAD

**Issue by 1581-netizen** [Alyetama/Gofile#1]
Good Morning,

It is possible to upload multiple files in the same url?
Obviously depending on the space available and the active plan 

Thanks

**Comment by Alyetama** [comment]
Yes, it is possible. I will add support to uploading multiple files to the same URL soon.

**Comment by Alyetama** [comment]
@1581-netizen This feature is now implemented in the latest release `0.3.0` ([example](https://github.com/Alyetama/Gofile#example-3-uploading-multiple-files-to-the-same-url)). Update your installation of the package to use it.

```sh
pip install -U gofilepy
```

**Comment by Alyetama** [comment]
Solved in 387207c720152710ee9da4f9fd12c449eeed8d71.
