### ISSUE TITLE
Upload Files is failing after latest gofile API Update

### ISSUE THREAD

**Issue by swapnilg4u** [Alyetama/Gofile#3]
Hi, I am a frequent user of GoFile and your project just makes my task a lot easier. Thanks for that :) However, from the last update (12 June) the upload command is giving error. It'll be great if you could push a fix for it.
<img width="882" alt="image" src="https://github.com/Alyetama/Gofile/assets/66756037/037a7026-7d06-4c80-af80-d7c529d1e4c2">

**Comment by Alyetama** [comment]
Looking into this. Thanks for reporting the issue!

**Comment by Alyetama** [comment]
I was unable to replicate the error on my end; everything seems to be working fine. Could you please provide the full command you used? Additionally, could you try re-running the command with `-vv` to see if the issue persists?
Thank you.

**Comment by swapnilg4u** [comment]
Hi, sorry for late response but I just tried uploading right now and it worked! I'm sure there would be some issue with the gofile developers side that caused the issue that particular day. I thought since they gave an update related to API so now the code has to be modified. Anyways thanks for quick response.
Closing this issue now.
