### ISSUE TITLE
Upload Progress Is Not Working

### ISSUE THREAD

**Issue by rajeshsahoo12** [Alyetama/Gofile#4]
Hi Dev,

I am using this project & it is really easy to use. Thanks for it.

But when I am using it to upload the content of the folder which multiple files. Upload progress is not working & there is not timer running. Here is the cmd I am using.

`gofile "C:\Users\Rajesh Sahoo\Desktop\Music Rippers\apple-music-alac-atmos-downloader-zhaarey\AM-DL-Atmos downloads"`

I am on windows 10 based PC. 

![image](https://github.com/Alyetama/Gofile/assets/54216637/06cb7aa0-1264-4f92-a522-1a8b07bd791d)

Thanks

**Comment by rajeshsahoo12** [comment]
> Hi Dev,
> 
> I am using this project & it is really easy to use. Thanks for it.
> 
> But when I am using it to upload the content of the folder which multiple files. Upload progress is not working & there is not timer running. Here is the cmd I am using.
> 
> `gofile "C:\Users\Rajesh Sahoo\Desktop\Music Rippers\apple-music-alac-atmos-downloader-zhaarey\AM-DL-Atmos downloads"`
> 
> I am on windows 10 based PC.
> 
> ![image](https://private-user-images.githubusercontent.com/54216637/342719312-06cb7aa0-1264-4f92-a522-1a8b07bd791d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTc3MjEsIm5iZiI6MTcxOTMxNzQyMSwicGF0aCI6Ii81NDIxNjYzNy8zNDI3MTkzMTItMDZjYjdhYTAtMTI2NC00ZjkyLWE1MjItMWE4YjA3YmQ3OTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDEyMTAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxN2Y3MzAzMGZkNzkzNGMxYzE0NmVjNzQ3OTMzZTFjZGFiMjgyYmEzMzMwZTM0OTQ0ZjUxZjZjMjdiZDc0OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4V7ZdkyYS-KtMVZtMi3j1nULSTyUeRXfGew9J0EwdOQ)
> 
> Thanks

After uploading complete of one file it shows this. But the progress is not updating in real time.

![image](https://github.com/Alyetama/Gofile/assets/54216637/1b70eba6-7425-43ca-920c-e7079c4409ab)

**Comment by Alyetama** [comment]
This is normal behavior. The progress bar tracks per file, not per byte. So if you upload 1 file, it will be 100% after the file is uploaded. If you upload 2 files, it will be 50% after the first file is uploaded and then 100% after the second file is uploaded.

**Comment by rajeshsahoo12** [comment]
> This is normal behavior. The progress bar tracks per file, not per byte. So if you upload 1 file, it will be 100% after the file is uploaded. If you upload 2 files, it will be 50% after the first file is uploaded and then 100% after the second file is uploaded.

Okay thanks dev.
