### ISSUE TITLE
Sometime This Issue Comes

### ISSUE THREAD

**Issue by rajeshsahoo12** [Alyetama/Gofile#5]
Hi Dev,

I get sometimes this error. How to work this out...?

![image](https://github.com/Alyetama/Gofile/assets/54216637/68bf71b6-5192-43f5-b78b-0ed0c3b65a15)

Error log is attached here `https://hastebin.com/share/aharedamox.vbnet`

Thanks

**Comment by Alyetama** [comment]
Hi,
How often do you encounter this issue? Sometimes the problem is on the API side and not with this program.
Thank you!

**Comment by rajeshsahoo12** [comment]
> How often do you encounter this issue?

Let say 2-3 times out of 10 times in total. I do suspected that. Okay. Thanks dev.
